name: todo_list_app
publish_to: 'none'
description: A production-ready Flutter Todo App with Firebase, Riverpod, Material 3, Sentry, and Hive.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.6
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  flutter_riverpod: ^2.4.9
  flutter_slidable: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sentry_flutter: ^8.14.2
  intl: ^0.20.2
  uuid: ^4.2.2
  lottie: ^3.3.1
  material_color_utilities: ^0.11.1

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true