// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA63opADJtRFdNwg4xJsAnE35cZqmVdN-o',
    appId: '1:620372050854:web:eb30203a0aede39aedc567',
    messagingSenderId: '620372050854',
    projectId: 'todolist-app-dffe5',
    authDomain: 'todolist-app-dffe5.firebaseapp.com',
    storageBucket: 'todolist-app-dffe5.firebasestorage.app',
    measurementId: 'G-5QJ9P7XRSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqv5f0CmqJju3vtwUkznYfVNI0Nc2qFzc',
    appId: '1:620372050854:android:dfde7d12ee797d34edc567',
    messagingSenderId: '620372050854',
    projectId: 'todolist-app-dffe5',
    storageBucket: 'todolist-app-dffe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE8F5Y3bcrl5MKa0LzKfXCET3wTSC9i0Q',
    appId: '1:620372050854:ios:48d7f9cb3d6cec67edc567',
    messagingSenderId: '620372050854',
    projectId: 'todolist-app-dffe5',
    storageBucket: 'todolist-app-dffe5.firebasestorage.app',
    iosClientId: '620372050854-vkkmsiapvooc8q56eb908t4tb95f1d9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE8F5Y3bcrl5MKa0LzKfXCET3wTSC9i0Q',
    appId: '1:620372050854:ios:48d7f9cb3d6cec67edc567',
    messagingSenderId: '620372050854',
    projectId: 'todolist-app-dffe5',
    storageBucket: 'todolist-app-dffe5.firebasestorage.app',
    iosClientId: '620372050854-vkkmsiapvooc8q56eb908t4tb95f1d9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA63opADJtRFdNwg4xJsAnE35cZqmVdN-o',
    appId: '1:620372050854:web:6e1e2e4926c97b85edc567',
    messagingSenderId: '620372050854',
    projectId: 'todolist-app-dffe5',
    authDomain: 'todolist-app-dffe5.firebaseapp.com',
    storageBucket: 'todolist-app-dffe5.firebasestorage.app',
    measurementId: 'G-6VGB9YES18',
  );
}
